// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase options for project: skillswap-3e33f
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkCbeANZzjYhLRo6r7UfTq-hHrRRfPtE',
    appId: '1:2081006226:web:2dda5dceaf8efb1d2cbc4b',
    messagingSenderId: '2081006226',
    projectId: 'skillswap-3e33f',
    authDomain: 'skillswap-3e33f.firebaseapp.com',
    storageBucket: 'skillswap-3e33f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbkCbeANZzjYhLRo6r7UfTq-hHrRRfPtE',
    appId: '1:2081006226:android:ddab812f8892d4a62cbc4b',
    messagingSenderId: '2081006226',
    projectId: 'skillswap-3e33f',
    storageBucket: 'skillswap-3e33f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbkCbeANZzjYhLRo6r7UfTq-hHrRRfPtE',
    appId: '1:2081006226:android:ddab812f8892d4a62cbc4b',
    messagingSenderId: '2081006226',
    projectId: 'skillswap-3e33f',
    storageBucket: 'skillswap-3e33f.firebasestorage.app',
    iosBundleId: 'com.skillswap.skillSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbkCbeANZzjYhLRo6r7UfTq-hHrRRfPtE',
    appId: '1:2081006226:android:ddab812f8892d4a62cbc4b',
    messagingSenderId: '2081006226',
    projectId: 'skillswap-3e33f',
    storageBucket: 'skillswap-3e33f.firebasestorage.app',
    iosBundleId: 'com.skillswap.skillSwap',
  );
}
