/// UI and app-wide constants.
class AppConstants {
  AppConstants._();

  static const double paddingXS = 4;
  static const double paddingS = 8;
  static const double paddingM = 16;
  static const double paddingL = 24;
  static const double paddingXL = 32;

  static const double radiusS = 8;
  static const double radiusM = 12;
  static const double radiusL = 16;
  static const double radiusXL = 24;

  static const Duration animationFast = Duration(milliseconds: 200);
  static const Duration animationNormal = Duration(milliseconds: 350);
  static const Duration animationSlow = Duration(milliseconds: 500);

  static const String onboardingKey = 'onboarding_complete';
  static const String themeKey = 'theme_mode';

  static const List<String> experienceLevels = [
    'Beginner',
    'Intermediate',
    'Advanced',
    'Expert',
  ];

  static const List<String> skillCategories = [
    'Development',
    'Design',
    'Marketing',
    'Music',
    'Language',
    'Business',
    'Photography',
    'Writing',
    'Fitness',
    'Other',
  ];

  /// Max skills a user can select for teach / learn.
  static const int maxSkillsPerCategory = 3;

  /// Predefined skills organised by category.
  static const Map<String, List<String>> predefinedSkills = {
    'Development': [
      'Flutter',
      'Dart',
      'React',
      'Angular',
      'Vue.js',
      'Next.js',
      'Node.js',
      'Express.js',
      'Python',
      'Django',
      'FastAPI',
      'Java',
      'Spring Boot',
      'Kotlin',
      'Swift',
      'iOS Development',
      'Android Development',
      'Web Development',
      'JavaScript',
      'TypeScript',
      'HTML & CSS',
      'C++',
      'C#',
      '.NET',
      'Go',
      'Rust',
      'Ruby on Rails',
      'PHP',
      'Laravel',
      'React Native',
      'Firebase',
      'AWS',
      'Azure',
      'Google Cloud',
      'Docker',
      'Kubernetes',
      'CI/CD',
      'Git & GitHub',
      'REST API Design',
      'GraphQL',
      'MongoDB',
      'PostgreSQL',
      'Redis',
      'Machine Learning',
      'Deep Learning',
      'Data Science',
      'NLP',
      'Computer Vision',
      'Blockchain',
      'Solidity',
    ],
    'Design': [
      'UI/UX Design',
      'Figma',
      'Adobe XD',
      'Sketch',
      'Graphic Design',
      'Logo Design',
      'Brand Identity',
      'Illustration',
      'Motion Graphics',
      'After Effects',
      '3D Modeling',
      'Blender',
      'Product Design',
      'Design Systems',
      'Prototyping',
      'User Research',
      'Wireframing',
    ],
    'Marketing': [
      'Digital Marketing',
      'SEO',
      'Content Strategy',
      'Social Media Marketing',
      'Google Ads',
      'Facebook Ads',
      'Email Marketing',
      'Copywriting',
      'Growth Hacking',
      'Analytics',
      'Marketing Automation',
      'Influencer Marketing',
      'Branding',
    ],
    'Music': [
      'Piano',
      'Guitar',
      'Vocals',
      'Drums',
      'Violin',
      'Music Theory',
      'Music Production',
      'Ableton',
      'FL Studio',
      'Logic Pro',
      'Sound Engineering',
      'Songwriting',
      'DJing',
    ],
    'Language': [
      'English',
      'Spanish',
      'French',
      'German',
      'Mandarin',
      'Japanese',
      'Korean',
      'Arabic',
      'Portuguese',
      'Italian',
      'Hindi',
      'Urdu',
      'Russian',
      'Turkish',
    ],
    'Business': [
      'Entrepreneurship',
      'Startup Strategy',
      'Product Management',
      'Project Management',
      'Agile & Scrum',
      'Finance',
      'Accounting',
      'Excel & Sheets',
      'Data Analysis',
      'Public Speaking',
      'Negotiation',
      'Leadership',
      'Consulting',
    ],
    'Photography': [
      'Photography',
      'Portrait Photography',
      'Landscape Photography',
      'Photo Editing',
      'Lightroom',
      'Photoshop',
      'Video Editing',
      'Premiere Pro',
      'DaVinci Resolve',
      'Cinematography',
      'Drone Filming',
      'YouTube Content',
      'Short-form Video',
    ],
    'Writing': [
      'Creative Writing',
      'Technical Writing',
      'Blogging',
      'Content Writing',
      'Screenwriting',
      'Poetry',
      'Journalism',
      'Ghostwriting',
      'Editing & Proofreading',
      'Publishing',
    ],
    'Fitness': [
      'Fitness Training',
      'Yoga',
      'Meditation',
      'Nutrition',
      'Weightlifting',
      'Running & Marathon',
      'Martial Arts',
      'Boxing',
      'Swimming',
      'Calisthenics',
      'Pilates',
      'Sports Coaching',
    ],
    'Other': [
      'Cooking',
      'Baking',
      'Gardening',
      'Interior Design',
      'Fashion Design',
      'Makeup & Beauty',
      'Hair Styling',
      'Crafts & DIY',
      'Painting',
      'Calligraphy',
      'Chess',
      'Board Games',
      'Teaching & Tutoring',
      'Counseling',
      'Life Coaching',
    ],
  };
}
